/**
* This file was @generated by a custom typegen script.
*/

export enum Collections {
	_mfas = "_mfas",
	_otps = "_otps",
	_externalAuths = "_externalAuths",
	_authOrigins = "_authOrigins",
	_superusers = "_superusers",
	Users = "users",
	Countries = "countries",
	Regions = "regions",
	Clubs = "clubs",
	Club_memberships = "club_memberships",
	Programs = "programs",
	Club_years = "club_years",
	Clubbers = "clubbers",
	Clubber_registrations = "clubber_registrations",
	Events = "events",
	Attendance = "attendance",
	Admin_roles = "admin_roles",
}

// Alias types for improved usability
export type IsoDateString = string
export type RecordIdString = string
export type HTMLString = string

// System fields
export type BaseSystemFields<T = never> = {
	id: RecordIdString
	created: IsoDateString
	updated: IsoDateString
	collectionId: string
	collectionName: Collections
	expand?: T
}

export type AuthSystemFields<T = never> = {
	email: string
	emailVisibility: boolean
	username: string
	verified: boolean
} & BaseSystemFields<T>

// Record types for _mfas
export type _mfasRecord = {
}

export type _mfasResponse<Texpand = unknown> = Required<_mfasRecord> & BaseSystemFields<Texpand>

// Record types for _otps
export type _otpsRecord = {
}

export type _otpsResponse<Texpand = unknown> = Required<_otpsRecord> & BaseSystemFields<Texpand>

// Record types for _externalAuths
export type _externalAuthsRecord = {
}

export type _externalAuthsResponse<Texpand = unknown> = Required<_externalAuthsRecord> & BaseSystemFields<Texpand>

// Record types for _authOrigins
export type _authOriginsRecord = {
}

export type _authOriginsResponse<Texpand = unknown> = Required<_authOriginsRecord> & BaseSystemFields<Texpand>

// Record types for _superusers
export type _superusersRecord = {
}

export type _superusersResponse<Texpand = unknown> = Required<_superusersRecord> & AuthSystemFields<Texpand>

// Record types for users
export type UsersRecord = {
	name?: string
	avatar?: string
	displayName?: string
	bio?: string
	created?: any
	updated?: any
	language?: string
	locale?: string
	theme?: string
	phone?: string
}

export type UsersResponse<Texpand = unknown> = Required<UsersRecord> & AuthSystemFields<Texpand>

// Record types for countries
export type CountriesRecord = {
	name: string
	isoCode?: string
}

export type CountriesResponse<Texpand = unknown> = Required<CountriesRecord> & BaseSystemFields<Texpand>

// Record types for regions
export type RegionsRecord = {
	name: string
	country: RecordIdString[]
}

export type RegionsResponse<Texpand = unknown> = Required<RegionsRecord> & BaseSystemFields<Texpand>

// Record types for clubs
export type ClubsRecord = {
	name: string
	type: "Leader Based" | "Other"
	region: RecordIdString[]
	address?: string
	timezone?: string
	active?: boolean
	registration?: string
	denomination?: string
	location?: string
	missionary?: RecordIdString[]
	expiration?: string
	metadata?: null | any
	salesforce?: string
	venue: "Church" | "School" | "Community Center" | "Christian Camp" | "Children's Ministry Office" | "Mission Compound" | "Refugee Camp" | "Youth Center" | "Orphanage" | "Other"
	country: RecordIdString
	joinCode?: string
	leaderSecret?: string
	lat?: number
	lng?: number
}

export type ClubsResponse<Texpand = unknown> = Required<ClubsRecord> & BaseSystemFields<Texpand>

// Record types for club_memberships
export type Club_membershipsRecord = {
	user: RecordIdString[]
	club: RecordIdString[]
	roles: "Director" | "Secretary" | "Treasurer" | "Leader" | "Guardian" | "Pending"
}

export type Club_membershipsResponse<Texpand = unknown> = Required<Club_membershipsRecord> & BaseSystemFields<Texpand>

// Record types for programs
export type ProgramsRecord = {
	club: RecordIdString[]
	name: string
	description?: string
}

export type ProgramsResponse<Texpand = unknown> = Required<ProgramsRecord> & BaseSystemFields<Texpand>

// Record types for club_years
export type Club_yearsRecord = {
	club: RecordIdString[]
	label: string
	startDate: string
	endDate: string
}

export type Club_yearsResponse<Texpand = unknown> = Required<Club_yearsRecord> & BaseSystemFields<Texpand>

// Record types for clubbers
export type ClubbersRecord = {
	club: RecordIdString[]
	firstName: string
	lastName: string
	dateOfBirth?: string
	notes?: string
	guardian?: RecordIdString
	active?: boolean
	gender?: "Male" | "Female"
}

export type ClubbersResponse<Texpand = unknown> = Required<ClubbersRecord> & BaseSystemFields<Texpand>

// Record types for clubber_registrations
export type Clubber_registrationsRecord = {
	clubber: RecordIdString[]
	club_year: RecordIdString[]
	program: RecordIdString[]
	club: RecordIdString[]
}

export type Clubber_registrationsResponse<Texpand = unknown> = Required<Clubber_registrationsRecord> & BaseSystemFields<Texpand>

// Record types for events
export type EventsRecord = {
	club?: RecordIdString[]
	club_year: RecordIdString[]
	name: string
	type: "Weekly" | "Games" | "Quiz" | "Other"
	startDate: string
	endDate: string
	region?: RecordIdString[]
}

export type EventsResponse<Texpand = unknown> = Required<EventsRecord> & BaseSystemFields<Texpand>

// Record types for attendance
export type AttendanceRecord = {
	event: RecordIdString[]
	student: RecordIdString[]
	status: "Present" | "Absent" | "Excused"
	club: RecordIdString[]
}

export type AttendanceResponse<Texpand = unknown> = Required<AttendanceRecord> & BaseSystemFields<Texpand>

// Record types for admin_roles
export type Admin_rolesRecord = {
	user: RecordIdString[]
	role: "Pending" | "Global" | "Country" | "Region"
	country?: RecordIdString[]
	region?: RecordIdString[]
}

export type Admin_rolesResponse<Texpand = unknown> = Required<Admin_rolesRecord> & BaseSystemFields<Texpand>

export type CollectionRecords = {
	_mfas: _mfasRecord
	_otps: _otpsRecord
	_externalAuths: _externalAuthsRecord
	_authOrigins: _authOriginsRecord
	_superusers: _superusersRecord
	users: UsersRecord
	countries: CountriesRecord
	regions: RegionsRecord
	clubs: ClubsRecord
	club_memberships: Club_membershipsRecord
	programs: ProgramsRecord
	club_years: Club_yearsRecord
	clubbers: ClubbersRecord
	clubber_registrations: Clubber_registrationsRecord
	events: EventsRecord
	attendance: AttendanceRecord
	admin_roles: Admin_rolesRecord
}

export type CollectionResponses = {
	_mfas: _mfasResponse
	_otps: _otpsResponse
	_externalAuths: _externalAuthsResponse
	_authOrigins: _authOriginsResponse
	_superusers: _superusersResponse
	users: UsersResponse
	countries: CountriesResponse
	regions: RegionsResponse
	clubs: ClubsResponse
	club_memberships: Club_membershipsResponse
	programs: ProgramsResponse
	club_years: Club_yearsResponse
	clubbers: ClubbersResponse
	clubber_registrations: Clubber_registrationsResponse
	events: EventsResponse
	attendance: AttendanceResponse
	admin_roles: Admin_rolesResponse
}
