/**
* This file was @generated by a custom typegen script.
* It extracts the schema from the latest collections snapshot migration.
*/

export enum Collections {
	Mfas = "_mfas",
	Otps = "_otps",
	ExternalAuths = "_externalAuths",
	AuthOrigins = "_authOrigins",
	Superusers = "_superusers",
	Users = "users",
	Countries = "countries",
	Regions = "regions",
	Clubs = "clubs",
	ClubMemberships = "club_memberships",
	Programs = "programs",
	ClubYears = "club_years",
	Clubbers = "clubbers",
	ClubberRegistrations = "clubber_registrations",
	Events = "events",
	Attendance = "attendance",
	AdminRoles = "admin_roles",
}

// Alias types for improved usability
export type IsoDateString = string
export type RecordIdString = string
export type HTMLString = string

// System fields
export type BaseSystemFields<T = never> = {
	id: RecordIdString
	created: IsoDateString
	updated: IsoDateString
	collectionId: string
	collectionName: Collections
	expand?: T
}

export type AuthSystemFields<T = never> = {
	email: string
	emailVisibility: boolean
	username: string
	verified: boolean
} & BaseSystemFields<T>

// Record types for _mfas
export type MfasRecord = {
}

export type MfasResponse<Texpand = unknown> = Required<MfasRecord> & BaseSystemFields<Texpand>

// Record types for _otps
export type OtpsRecord = {
}

export type OtpsResponse<Texpand = unknown> = Required<OtpsRecord> & BaseSystemFields<Texpand>

// Record types for _externalAuths
export type ExternalAuthsRecord = {
}

export type ExternalAuthsResponse<Texpand = unknown> = Required<ExternalAuthsRecord> & BaseSystemFields<Texpand>

// Record types for _authOrigins
export type AuthOriginsRecord = {
}

export type AuthOriginsResponse<Texpand = unknown> = Required<AuthOriginsRecord> & BaseSystemFields<Texpand>

// Record types for _superusers
export type SuperusersRecord = {
}

export type SuperusersResponse<Texpand = unknown> = Required<SuperusersRecord> & AuthSystemFields<Texpand>

// Record types for users
export type UsersRecord = {
	name?: string
	avatar?: string
	displayName?: string
	bio?: string
	language?: string
	locale?: string
	theme?: string
	phone?: string
}

export type UsersResponse<Texpand = unknown> = Required<UsersRecord> & AuthSystemFields<Texpand>

// Record types for countries
export type CountriesRecord = {
	name: string
	isoCode?: string
}

export type CountriesResponse<Texpand = unknown> = Required<CountriesRecord> & BaseSystemFields<Texpand>

// Record types for regions
export type RegionsRecord = {
	name: string
	country: RecordIdString[]
}

export type RegionsResponse<Texpand = unknown> = Required<RegionsRecord> & BaseSystemFields<Texpand>

// Record types for clubs
export type ClubsRecord = {
	name: string
	type: "Leader Based" | "Other"
	region: RecordIdString[]
	address?: string
	timezone?: string
	active?: boolean
	registration?: string
	denomination?: string
	location?: string
	missionary?: RecordIdString[]
	expiration?: string
	metadata?: any
	salesforce?: string
	venue: "Church" | "School" | "Community Center" | "Christian Camp" | "Children's Ministry Office" | "Mission Compound" | "Refugee Camp" | "Youth Center" | "Orphanage" | "Other"
	country: RecordIdString
	joinCode?: string
	leaderSecret?: string
	lat?: number
	lng?: number
}

export type ClubsResponse<Texpand = unknown> = Required<ClubsRecord> & BaseSystemFields<Texpand>

// Record types for club_memberships
export type ClubMembershipsRecord = {
	user: RecordIdString[]
	club: RecordIdString[]
	roles: "Director" | "Secretary" | "Treasurer" | "Leader" | "Guardian" | "Pending"
}

export type ClubMembershipsResponse<Texpand = unknown> = Required<ClubMembershipsRecord> & BaseSystemFields<Texpand>

// Record types for programs
export type ProgramsRecord = {
	club: RecordIdString[]
	name: string
	description?: string
}

export type ProgramsResponse<Texpand = unknown> = Required<ProgramsRecord> & BaseSystemFields<Texpand>

// Record types for club_years
export type ClubYearsRecord = {
	club: RecordIdString[]
	label: string
	startDate: string
	endDate: string
}

export type ClubYearsResponse<Texpand = unknown> = Required<ClubYearsRecord> & BaseSystemFields<Texpand>

// Record types for clubbers
export type ClubbersRecord = {
	club: RecordIdString[]
	firstName: string
	lastName: string
	dateOfBirth?: string
	notes?: string
	guardian?: RecordIdString
	active?: boolean
	gender?: "Male" | "Female"
}

export type ClubbersResponse<Texpand = unknown> = Required<ClubbersRecord> & BaseSystemFields<Texpand>

// Record types for clubber_registrations
export type ClubberRegistrationsRecord = {
	clubber: RecordIdString[]
	club_year: RecordIdString[]
	program: RecordIdString[]
	club: RecordIdString[]
}

export type ClubberRegistrationsResponse<Texpand = unknown> = Required<ClubberRegistrationsRecord> & BaseSystemFields<Texpand>

// Record types for events
export type EventsRecord = {
	club?: RecordIdString[]
	club_year: RecordIdString[]
	name: string
	type: "Weekly" | "Games" | "Quiz" | "Other"
	startDate: string
	endDate: string
	region?: RecordIdString[]
}

export type EventsResponse<Texpand = unknown> = Required<EventsRecord> & BaseSystemFields<Texpand>

// Record types for attendance
export type AttendanceRecord = {
	event: RecordIdString[]
	student: RecordIdString[]
	status: "Present" | "Absent" | "Excused"
	club: RecordIdString[]
}

export type AttendanceResponse<Texpand = unknown> = Required<AttendanceRecord> & BaseSystemFields<Texpand>

// Record types for admin_roles
export type AdminRolesRecord = {
	user: RecordIdString[]
	role: "Pending" | "Global" | "Country" | "Region"
	country?: RecordIdString[]
	region?: RecordIdString[]
}

export type AdminRolesResponse<Texpand = unknown> = Required<AdminRolesRecord> & BaseSystemFields<Texpand>

export type CollectionRecords = {
	_mfas: MfasRecord
	_otps: OtpsRecord
	_externalAuths: ExternalAuthsRecord
	_authOrigins: AuthOriginsRecord
	_superusers: SuperusersRecord
	users: UsersRecord
	countries: CountriesRecord
	regions: RegionsRecord
	clubs: ClubsRecord
	club_memberships: ClubMembershipsRecord
	programs: ProgramsRecord
	club_years: ClubYearsRecord
	clubbers: ClubbersRecord
	clubber_registrations: ClubberRegistrationsRecord
	events: EventsRecord
	attendance: AttendanceRecord
	admin_roles: AdminRolesRecord
}

export type CollectionResponses = {
	_mfas: MfasResponse
	_otps: OtpsResponse
	_externalAuths: ExternalAuthsResponse
	_authOrigins: AuthOriginsResponse
	_superusers: SuperusersResponse
	users: UsersResponse
	countries: CountriesResponse
	regions: RegionsResponse
	clubs: ClubsResponse
	club_memberships: ClubMembershipsResponse
	programs: ProgramsResponse
	club_years: ClubYearsResponse
	clubbers: ClubbersResponse
	clubber_registrations: ClubberRegistrationsResponse
	events: EventsResponse
	attendance: AttendanceResponse
	admin_roles: AdminRolesResponse
}
