import fs from 'fs';

// Helper to read the snapshot from the migration file
const migrationFile = fs.readdirSync('pb_migrations').find(f => f.includes('collections_snapshot.js'));
if (!migrationFile) {
  console.error("No snapshot migration found.");
  process.exit(1);
}

const content = fs.readFileSync(`pb_migrations/${migrationFile}`, 'utf8');
const snapshotMatch = content.match(/const snapshot = (\[[\s\S]*?\]);/);
if (!snapshotMatch) {
  console.error("Could not find snapshot in migration file.");
  process.exit(1);
}

const snapshot = JSON.parse(snapshotMatch[1]);

function generateTypes(collections) {
  let out = `/**
* This file was @generated by a custom typegen script.
*/

export enum Collections {
${collections.map(c => `\t${c.name.charAt(0).toUpperCase() + c.name.slice(1)} = "${c.name}",`).join('\n')}
}

// Alias types for improved usability
export type IsoDateString = string
export type RecordIdString = string
export type HTMLString = string

// System fields
export type BaseSystemFields<T = never> = {
\tid: RecordIdString
\tcreated: IsoDateString
\tupdated: IsoDateString
\tcollectionId: string
\tcollectionName: Collections
\texpand?: T
}

export type AuthSystemFields<T = never> = {
\temail: string
\temailVisibility: boolean
\tusername: string
\tverified: boolean
} & BaseSystemFields<T>

`;

  for (const collection of collections) {
    const typeName = collection.name.charAt(0).toUpperCase() + collection.name.slice(1);
    const responseName = `${typeName}Response`;
    const recordName = `${typeName}Record`;

    out += `// Record types for ${collection.name}\n`;
    out += `export type ${recordName} = {\n`;
    
    for (const field of collection.fields) {
      if (field.system) continue;
      
      let type = 'any';
      switch (field.type) {
        case 'text':
        case 'email':
        case 'url':
        case 'date':
          type = 'string';
          break;
        case 'number':
          type = 'number';
          break;
        case 'bool':
          type = 'boolean';
          break;
        case 'json':
          type = 'null | any';
          break;
        case 'file':
          type = field.maxSelect === 1 ? 'string' : 'string[]';
          break;
        case 'relation':
          type = field.maxSelect === 1 ? 'RecordIdString' : 'RecordIdString[]';
          break;
        case 'select':
          type = field.values.map(v => `"${v}"`).join(' | ');
          break;
      }
      
      const optional = field.required ? '' : '?';
      out += `\t${field.name}${optional}: ${type}\n`;
    }
    out += `}\n\n`;

    const systemFields = collection.type === 'auth' ? 'AuthSystemFields' : 'BaseSystemFields';
    out += `export type ${responseName}<Texpand = unknown> = Required<${recordName}> & ${systemFields}<Texpand>\n\n`;
  }

  out += `export type CollectionRecords = {\n`;
  for (const collection of collections) {
    out += `\t${collection.name}: ${collection.name.charAt(0).toUpperCase() + collection.name.slice(1)}Record\n`;
  }
  out += `}\n\n`;

  out += `export type CollectionResponses = {\n`;
  for (const collection of collections) {
    out += `\t${collection.name}: ${collection.name.charAt(0).toUpperCase() + collection.name.slice(1)}Response\n`;
  }
  out += `}\n`;

  return out;
}

const generated = generateTypes(snapshot);
fs.writeFileSync('src/types/pocketbase-types.ts', generated);
console.log("Types generated successfully in src/types/pocketbase-types.ts");
